### ISSUE TITLE
Running E-MAML on KrazyWorld

### ISSUE THREAD

**Issue by alversafa** [episodeyang/e-maml#1]
Is it possible for you to be a bit more precise on what to do to run the algorithm on KrazyWorld?

What does "add a thin adaptor following the convention in `custom_vendor` and `sampler.py`" exactly mean?

**Comment by geyang** [comment]
Hi Safa! The meta-learning process requires a `reset_task` method to be available from the environment. I have not had the time to look at the new KrazyWorld implementation yet, so am not sure if it has that method implemented. Otherwise, the environment should be the same as regular gym environments.

The some of the calls to the environments can be found here: [meta_rl_tasks](https://github.com/episodeyang/e-maml/blob/eb9e55c7d4b00296c4bda08bcebc6b287192fa85/e_maml_tf/meta_rl_tasks.py#L102)

For a more comprehensive list of usage see this [link](https://github.com/episodeyang/e-maml/search?q=envs%5C.&unscoped_q=envs%5C.)

Here is the code that connects with the old KrazyWorld implementation: [maze_env.py#L49](https://github.com/episodeyang/e-maml/blob/master/e_maml_tf/custom_vendor/maze_env.py#L49)

Hope this helps!
